<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Pybullet on Dan Aukes</title><link>https://danaukes.com/tags/pybullet/</link><description>Recent content in Pybullet on Dan Aukes</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><atom:link href="https://danaukes.com/tags/pybullet/index.xml" rel="self" type="application/rss+xml"/><item><title>Building PyBullet</title><link>https://danaukes.com/notebook/deprecated/building-pybullet/</link><pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate><guid>https://danaukes.com/notebook/deprecated/building-pybullet/</guid><description>sudo apt install cmake-curses-gui cd ~/Downloads git clone https://github.com/bulletphysics/bullet3.git cd bullet3 ccmake .</description></item><item><title>getting pyBullet working in Anaconda</title><link>https://danaukes.com/notebook/deprecated/pybullet-in-anaconda/</link><pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate><guid>https://danaukes.com/notebook/deprecated/pybullet-in-anaconda/</guid><description>search keywords:
python anaconda conda pybullet Mesa OpenGL radeonsi swrast Trying to run a pyBullet script, I kept getting this kind of error:</description></item></channel></rss>